name: megg
description: "A fashion outfit app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.5.3
  phosphor_flutter: ^2.1.0
  video_player: ^2.9.1
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0
  share_plus: ^10.1.4
  path_provider: ^2.1.4
  lottie: ^3.3.2
  google_sign_in: ^6.2.1
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  flutter_secure_storage: ^10.0.0
  flutter_riverpod: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  chewie: ^1.13.0
  hugeicons: ^1.1.4
  connectivity_plus: ^7.0.0
  app_links: ^6.3.3
  flutter_image_compress: ^2.3.0
  image_cropper: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animatedlogo.mp4
    - assets/intro.mp4
    - assets/logo.png
    - assets/category/
    - assets/guides/
    - assets/animation.json

  fonts:
    - family: FuturaCyrillicBook
      fonts:
        - asset: assets/fonts/FuturaCyrillicBook.ttf
